/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as HopeCommunityHavenRouteImport } from './routes/hope-community-haven'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NobodyAskedMeRouteImport } from './routes/nobody-asked-me'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourceCenterRouteImport } from './routes/resource-center'
import { Route as AdminOrdersRouteImport } from './routes/admin_.orders'
import { Route as AdminShopRouteImport } from './routes/admin_.shop'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as EventsManageRouteImport } from './routes/events_.manage'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const HopeCommunityHavenRoute = HopeCommunityHavenRouteImport.update({
  id: '/hope-community-haven',
  path: '/hope-community-haven',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NobodyAskedMeRoute = NobodyAskedMeRouteImport.update({
  id: '/nobody-asked-me',
  path: '/nobody-asked-me',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceCenterRoute = ResourceCenterRouteImport.update({
  id: '/resource-center',
  path: '/resource-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin_/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/admin_/shop',
  path: '/admin/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsManageRoute = EventsManageRouteImport.update({
  id: '/events_/manage',
  path: '/events/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/desk': typeof DeskRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-involved': typeof GetInvolvedRoute
  '/hope-community-haven': typeof HopeCommunityHavenRoute
  '/impact': typeof ImpactRoute
  '/legacy': typeof LegacyRoute
  '/media': typeof MediaRoute
  '/nobody-asked-me': typeof NobodyAskedMeRoute
  '/partners': typeof PartnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resource-center': typeof ResourceCenterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/manage': typeof EventsManageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/desk': typeof DeskRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-involved': typeof GetInvolvedRoute
  '/hope-community-haven': typeof HopeCommunityHavenRoute
  '/impact': typeof ImpactRoute
  '/legacy': typeof LegacyRoute
  '/media': typeof MediaRoute
  '/nobody-asked-me': typeof NobodyAskedMeRoute
  '/partners': typeof PartnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resource-center': typeof ResourceCenterRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/manage': typeof EventsManageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/desk': typeof DeskRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-involved': typeof GetInvolvedRoute
  '/hope-community-haven': typeof HopeCommunityHavenRoute
  '/impact': typeof ImpactRoute
  '/legacy': typeof LegacyRoute
  '/media': typeof MediaRoute
  '/nobody-asked-me': typeof NobodyAskedMeRoute
  '/partners': typeof PartnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resource-center': typeof ResourceCenterRoute
  '/admin_/orders': typeof AdminOrdersRoute
  '/admin_/shop': typeof AdminShopRoute
  '/admin_/users': typeof AdminUsersRoute
  '/events_/manage': typeof EventsManageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/desk'
    | '/donate'
    | '/events'
    | '/forgot-password'
    | '/get-involved'
    | '/hope-community-haven'
    | '/impact'
    | '/legacy'
    | '/media'
    | '/nobody-asked-me'
    | '/partners'
    | '/reset-password'
    | '/resource-center'
    | '/admin/orders'
    | '/admin/shop'
    | '/admin/users'
    | '/events/manage'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/desk'
    | '/donate'
    | '/events'
    | '/forgot-password'
    | '/get-involved'
    | '/hope-community-haven'
    | '/impact'
    | '/legacy'
    | '/media'
    | '/nobody-asked-me'
    | '/partners'
    | '/reset-password'
    | '/resource-center'
    | '/admin/orders'
    | '/admin/shop'
    | '/admin/users'
    | '/events/manage'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/desk'
    | '/donate'
    | '/events'
    | '/forgot-password'
    | '/get-involved'
    | '/hope-community-haven'
    | '/impact'
    | '/legacy'
    | '/media'
    | '/nobody-asked-me'
    | '/partners'
    | '/reset-password'
    | '/resource-center'
    | '/admin_/orders'
    | '/admin_/shop'
    | '/admin_/users'
    | '/events_/manage'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  DeskRoute: typeof DeskRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  HopeCommunityHavenRoute: typeof HopeCommunityHavenRoute
  ImpactRoute: typeof ImpactRoute
  LegacyRoute: typeof LegacyRoute
  MediaRoute: typeof MediaRoute
  NobodyAskedMeRoute: typeof NobodyAskedMeRoute
  PartnersRoute: typeof PartnersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourceCenterRoute: typeof ResourceCenterRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminUsersRoute: typeof AdminUsersRoute
  EventsManageRoute: typeof EventsManageRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hope-community-haven': {
      id: '/hope-community-haven'
      path: '/hope-community-haven'
      fullPath: '/hope-community-haven'
      preLoaderRoute: typeof HopeCommunityHavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nobody-asked-me': {
      id: '/nobody-asked-me'
      path: '/nobody-asked-me'
      fullPath: '/nobody-asked-me'
      preLoaderRoute: typeof NobodyAskedMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-center': {
      id: '/resource-center'
      path: '/resource-center'
      fullPath: '/resource-center'
      preLoaderRoute: typeof ResourceCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/orders': {
      id: '/admin_/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/shop': {
      id: '/admin_/shop'
      path: '/admin/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/manage': {
      id: '/events_/manage'
      path: '/events/manage'
      fullPath: '/events/manage'
      preLoaderRoute: typeof EventsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  DeskRoute: DeskRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  HopeCommunityHavenRoute: HopeCommunityHavenRoute,
  ImpactRoute: ImpactRoute,
  LegacyRoute: LegacyRoute,
  MediaRoute: MediaRoute,
  NobodyAskedMeRoute: NobodyAskedMeRoute,
  PartnersRoute: PartnersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourceCenterRoute: ResourceCenterRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminShopRoute: AdminShopRoute,
  AdminUsersRoute: AdminUsersRoute,
  EventsManageRoute: EventsManageRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
